#!/bin/bash
#### sudo ./load_houses_params 01  команда запуска скрипта
SOURCE_PATH='/home/maksim/fias/'$1
DEST_PATH='/var/lib/postgresql' 
sed '1s/^\xEF\xBB\xBF//' < $SOURCE_PATH/AS_HOUSES_PARAMS_* > $SOURCE_PATH/houses_params.xml #перекодировали в UTF-8
cp -f $SOURCE_PATH/houses_params.xml $DEST_PATH/AS_HOUSES_PARAMS.XML  #скопировали в домашнюю директорию POSTGRESQL
cat psql_load_houses_params.sql | PGPASSWORD=momqV93V psql -h 127.0.0.1 -U shmv -d shmv #выполнили скрипт загрузки в базу
