#!/bin/bash
#### sudo ./load_addr 01  команда запуска скрипта
SOURCE_PATH='/home/maksim/fias/'$1
DEST_PATH='/var/lib/postgresql' 
sed '1s/^\xEF\xBB\xBF//' < $SOURCE_PATH/AS_ADDR_OBJ_20230112_* > $SOURCE_PATH/new.xml #перекодировали в UTF-8
cp -f $SOURCE_PATH/new.xml $DEST_PATH/AS_ADDR_OBJ_ALL.xml  #скопировали в домашнюю директорию POSTGRESQL
cat psql_load_addr_obj.sql | PGPASSWORD=momqV93V psql -h 127.0.0.1 -U shmv -d shmv #выполнили скрипт загрузки в базу
